site_name: "Peak Framework Docs"
site_description: "Official documentation for the Peak Framework"
copyright: "Francois Lajoie"
extra_css: ["css/style.css"]
pages:
  - "Peak Framework": 
    - "Overview": "index.md"
    - "Installation": "installation.md"
  - Components:
    - Di:
      - "Introduction": "components/di/introduction.md"
      - "Basic usage": "components/di/basic-usage.md"
      - "Create objects": "components/di/create.md"
      - "Advanced usage": "components/di/definitions.md"
